apiVersion: apps/v1 
kind: deployment 
metadata: 
  name: frontend-deployment 
  namespace: digi 
spec:
  replicas: 1
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: digi 

  template:
    metadata:
      app: digi 
    spec:
      containers:
        - name: digi-cont 
          image: muralisocial123/digital-bank:1.1.0
          ports:
            - containerPort: 4545
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "400Mi"
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: digi-sec
                  key: MONGODB_URI
            - name: PORT 
              valueFrom:
                secretKeyRef:
                  name: digi-sec
                  key: PORT

