apiVersion: rbac.authorization.k8s.io/v1 
kind: Role 
metadata: 
  name: pod-role 
  namespace: digi 
rules: #
  - apiGroups: [""]
    resources: ["pods","nodes","namespace"]
    verbs: ["create","list","delete","get","watch"]