apiVersion: v1
kind: Secret
metadata:
  name: digi-sec
  namespace: digi 
type: Opaque 
stringData: 
  MONGODB_URI: "mongodb://admin:admin123@host.docker.internal:27017/bank_transaction_system?authSource=admin"

  PORT: "4545"