apiVersion: v1
kind: Secret
metadata:
  name: digi-sec
  namespace: digi
type: Opaque
stringData:
  MONGODB_URI: "mongodb://root:root123@mongodb-headless.digi.svc.cluster.local:27017/mydb?authSource=admin&replicaSet=rs0"
  PORT: "4545"